export type Letter = string;

export const LETTER_SOUNDS: Record<Letter, any> = {
  А: require("../../app/assets/audio/a.m4a"),
  Б: require("../../app/assets/audio/b.m4a"),
  В: require("../../app/assets/audio/v.m4a"),
  Г: require("../../app/assets/audio/g.m4a"),
  Д: require("../../app/assets/audio/d.m4a"),
  Ѓ: require("../../app/assets/audio/gj.m4a"),
  Е: require("../../app/assets/audio/e.m4a"),
  Ж: require("../../app/assets/audio/zh.m4a"),
  З: require("../../app/assets/audio/z.m4a"),
  Ѕ: require("../../app/assets/audio/dz.m4a"),
  И: require("../../app/assets/audio/i.m4a"),
  Ј: require("../../app/assets/audio/j.m4a"),
  К: require("../../app/assets/audio/k.m4a"),
  Л: require("../../app/assets/audio/l.m4a"),
  Љ: require("../../app/assets/audio/lj.m4a"),
  М: require("../../app/assets/audio/m.m4a"),
  Н: require("../../app/assets/audio/n.m4a"),
  Њ: require("../../app/assets/audio/nj.m4a"),
  О: require("../../app/assets/audio/o.m4a"),
  П: require("../../app/assets/audio/p.m4a"),
  Р: require("../../app/assets/audio/r.m4a"),
  С: require("../../app/assets/audio/s.m4a"),
  Т: require("../../app/assets/audio/t.m4a"),
  Ќ: require("../../app/assets/audio/kj.m4a"),
  У: require("../../app/assets/audio/u.m4a"),
  Ф: require("../../app/assets/audio/f.m4a"),
  Х: require("../../app/assets/audio/h.m4a"),
  Ц: require("../../app/assets/audio/c.m4a"),
  Ч: require("../../app/assets/audio/ch.m4a"),
  Џ: require("../../app/assets/audio/dz.m4a"),
  Ш: require("../../app/assets/audio/sh.m4a"),
};

export const LETTER_IMAGES: Record<Letter, any> = {
  А: require("../../app/assets/images/a-avion.png"),
  Б: require("../../app/assets/images/b-banana.png"),
  В: require("../../app/assets/images/v-volk.png"),
  Г: require("../../app/assets/images/g-gevrek.png"),
  Д: require("../../app/assets/images/d-dedo.png"),
  Ѓ: require("../../app/assets/images/gj-gezve.png"),
  Е: require("../../app/assets/images/e-eze.png"),
  Ж: require("../../app/assets/images/z-zaba.png"),
  З: require("../../app/assets/images/z-zmija.png"),
  Ѕ: require("../../app/assets/images/dz-dzvezda.png"),
  И: require("../../app/assets/images/i-igla.png"),
  Ј: require("../../app/assets/images/j-jagoda.png"),
  К: require("../../app/assets/images/k-kapina.png"),
  Л: require("../../app/assets/images/l-limon.png"),
  Љ: require("../../app/assets/images/lj-ljubov.png"),
  М: require("../../app/assets/images/m-mravka.png"),
  Н: require("../../app/assets/images/n-nika.png"),
  Њ: require("../../app/assets/images/nj-njoki.png"),
  О: require("../../app/assets/images/o-osa.png"),
  П: require("../../app/assets/images/p-peperutka.png"),
  Р: require("../../app/assets/images/r-riba.png"),
  С: require("../../app/assets/images/s-sliva.png"),
  Т: require("../../app/assets/images/t-tigar.png"),
  Ќ: require("../../app/assets/images/kj-kjebe.png"),
  У: require("../../app/assets/images/u-uciliste.png"),
  Ф: require("../../app/assets/images/f-foka.png"),
  Х: require("../../app/assets/images/h-helikopter.png"),
  Ц: require("../../app/assets/images/c-cresha.png"),
  Ч: require("../../app/assets/images/ch-chador.png"),
  Џ: require("../../app/assets/images/dz-dzudze.png"),
  Ш: require("../../app/assets/images/sh-strk.png"),
};

export function hasLetter(v: string): v is Letter {
  return Object.prototype.hasOwnProperty.call(LETTER_IMAGES, v);
}
